env:
  node: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
